#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/.env"
SECRETS_PLIST="$ROOT/JukeboxHost/Resources/Secrets.plist"
SCHEME_DIR="$ROOT/JukeboxHost.xcodeproj/xcshareddata/xcschemes"
SCHEME_FILE="$SCHEME_DIR/JukeboxHost.xcscheme"

HOST_IP="${JUKEBOX_HOST_IP:-$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "127.0.0.1")}"

SPOTIFY_REDIRECT="http://${HOST_IP}:8765/api/auth/spotify/callback"
YOUTUBE_REDIRECT="http://${HOST_IP}:8765/api/auth/youtube/callback"

read_env_value() {
  local key="$1"
  if [[ -f "$ENV_FILE" ]]; then
    local line
    line="$(grep -E "^${key}=" "$ENV_FILE" | tail -1 || true)"
    if [[ -n "$line" ]]; then
      echo "${line#*=}"
      return
    fi
  fi
  echo ""
}

prompt_value() {
  local key="$1"
  local label="$2"
  local current
  current="$(read_env_value "$key")"
  if [[ -n "${!key:-}" ]]; then
    echo "${!key}"
    return
  fi
  if [[ -n "$current" ]]; then
    read -r -p "${label} [Enter=既存値を維持]: " input
    if [[ -z "$input" ]]; then
      echo "$current"
    else
      echo "$input"
    fi
  else
    read -r -p "${label}: " input
    echo "$input"
  fi
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/configure-api-credentials.sh
SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
EOF
  chmod 600 "$ENV_FILE"
}

write_secrets_plist() {
  cat >"$SECRETS_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>SPOTIFY_CLIENT_ID</key>
	<string>${SPOTIFY_CLIENT_ID}</string>
	<key>SPOTIFY_CLIENT_SECRET</key>
	<string>${SPOTIFY_CLIENT_SECRET}</string>
	<key>YOUTUBE_API_KEY</key>
	<string>${YOUTUBE_API_KEY}</string>
	<key>YOUTUBE_CLIENT_ID</key>
	<string>${YOUTUBE_CLIENT_ID}</string>
	<key>YOUTUBE_CLIENT_SECRET</key>
	<string>${YOUTUBE_CLIENT_SECRET}</string>
</dict>
</plist>
EOF
  chmod 600 "$SECRETS_PLIST"
}

sync_xcode_scheme() {
  mkdir -p "$SCHEME_DIR"
  if [[ ! -f "$SCHEME_FILE" ]]; then
    xcodegen generate
  fi
  python3 - "$SCHEME_FILE" "$ENV_FILE" <<'PY'
import plistlib
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

scheme_path = Path(sys.argv[1])
env_path = Path(sys.argv[2])

values = {}
if env_path.exists():
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()

keys = [
    "SPOTIFY_CLIENT_ID",
    "SPOTIFY_CLIENT_SECRET",
    "YOUTUBE_API_KEY",
    "YOUTUBE_CLIENT_ID",
    "YOUTUBE_CLIENT_SECRET",
]

tree = ET.parse(scheme_path)
root = tree.getroot()
launch = root.find("LaunchAction")
if launch is None:
    raise SystemExit("LaunchAction not found in scheme")

env_vars = launch.find("EnvironmentVariables")
if env_vars is None:
    env_vars = ET.SubElement(launch, "EnvironmentVariables")

existing = {node.attrib.get("key"): node for node in env_vars.findall("EnvironmentVariable")}
for key in keys:
    value = values.get(key, "")
    node = existing.get(key)
    if node is None:
        node = ET.SubElement(env_vars, "EnvironmentVariable")
        node.set("key", key)
        node.set("isEnabled", "YES")
    node.set("value", value)

tree.write(scheme_path, encoding="UTF-8", xml_declaration=True)
PY
}

open_console_pages() {
  echo ""
  echo "開発者コンソールを開きます。以下の Redirect URI を登録してください:"
  echo "  Spotify: $SPOTIFY_REDIRECT"
  echo "  YouTube: $YOUTUBE_REDIRECT"
  echo ""
  open "https://developer.spotify.com/dashboard" 2>/dev/null || true
  open "https://console.cloud.google.com/apis/credentials" 2>/dev/null || true
}

main() {
  echo "=== Jukebox API 認証設定 ==="
  echo "検出したホスト IP: $HOST_IP"
  echo ""

  SPOTIFY_CLIENT_ID="$(prompt_value SPOTIFY_CLIENT_ID "Spotify Client ID")"
  SPOTIFY_CLIENT_SECRET="$(prompt_value SPOTIFY_CLIENT_SECRET "Spotify Client Secret")"
  YOUTUBE_API_KEY="$(prompt_value YOUTUBE_API_KEY "YouTube API Key")"
  YOUTUBE_CLIENT_ID="$(prompt_value YOUTUBE_CLIENT_ID "YouTube OAuth Client ID")"
  YOUTUBE_CLIENT_SECRET="$(prompt_value YOUTUBE_CLIENT_SECRET "YouTube OAuth Client Secret")"

  write_env_file
  write_secrets_plist
  xcodegen generate
  sync_xcode_scheme

  echo ""
  echo "作成しました:"
  echo "  $ENV_FILE"
  echo "  $SECRETS_PLIST"
  echo "  $SCHEME_FILE (Environment Variables 同期済み)"
  echo ""
  echo "Redirect URI:"
  echo "  Spotify: $SPOTIFY_REDIRECT"
  echo "  YouTube: $YOUTUBE_REDIRECT"

  open_console_pages
}

main "$@"
